### PR TITLE
Fix #3653: Add a doctor helper to test pwd's.

### LINKED ISSUE #3653: Ensure the Dir.pwd and the actual working directory line up
Sometimes `Dir.pwd` returns the `$(pwd)` in downcased or otherwise incorrect form. In `jekyll doctor`, we should check this and it should be Windows-compatible as well.

Ref: https://github.com/jekyll/jekyll/issues/3624.

### PR DESCRIPTION
**Pull request by envygeeks**
This is just a basic test (as implied through a lot of the conversation) and will probably not suffice for all but according to what I have read, this basic test can detect most anomalies so we can warn you but it's not bulletproof by any means.

Ref: #3624
/cc @cjerdonek

### CODE REVIEW

File: lib/jekyll/commands/doctor.rb [hunk 1]
```diff
@@ -59,8 +60,24 @@ def conflicting_urls(site)
           conflicting_urls
         end
 
-        private
+        def fsnotify_buggy?(site)
+          return true if !Utils::Platforms.osx?
+          if Dir.pwd != `pwd`.strip
+            Jekyll.logger.error "  " + <<-STR.strip.gsub(/\n\s+/, "\n  ")
+              We have detected that there might be trouble using using
```
Comment (cjerdonek) [inline lib/jekyll/commands/doctor.rb]: "using using"

**Comment by cjerdonek** [comment]
Thanks for doing this.

File: lib/jekyll/commands/doctor.rb (hunk 1 above)
Comment (envygeeks) [inline lib/jekyll/commands/doctor.rb]: Fixed, and because of that you forced me to read the rest of it as a double check and I noticed I did `docker` instead of `doctor` in my platforms addition.

**Comment by parkr** [comment]
:shipit:
