### PR TITLE
Handle TypeError from `where` filter gracefully

### LINKED ISSUE #9289: [Bug]: Unexpected crash: filters.rb:442:in `read_liquid_attribute': no implicit conversion of String into Integer
### Operating System

OSX

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

### Jekyll Version

jekyll 4.2.1

### GitHub Pages Version

_No response_

### Expected Behavior

Should build without error

### Current Behavior

Crashes with a weird error:  filters.rb:442:in `read_liquid_attribute': no implicit conversion of String into Integer

### Relevant log output

```shell
/Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:442:in `read_liquid_attribute': no implicit conversion of String into Integer (TypeError)
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:430:in `item_property'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:199:in `block in where'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:198:in `select'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:198:in `where'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/inclusion.rb:16:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/tags/include.rb:208:in `block in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/tags/include.rb:206:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:131:in `render_liquid'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:80:in `render_document'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:63:in `run'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:547:in `render_regenerated'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:539:in `block in render_pages'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `each'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `render_pages'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:211:in `render'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/bin/jekyll:25:in `load'
	from /Users/grahamegrieve/.gem/ruby/3.1.0/bin/jekyll:25:in `<main>'
```

### Code Sample

See attached zip file. The error may be removed by removing the last entry in the json file pages/data/structuredefinitions.json (the "extensionContextsPopulated" : [ "none" ]) bit), or just converting it to "extensionContextsPopulated" : "none" 

[pages.zip](https://github.com/jekyll/jekyll/files/10576589/pages.zip)

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is a 🐛 bug fix.
- I've added tests.
- The test suite passes locally.

## Summary

Invoking `Array#[]` with a non-integer argument raises `no implicit conversion of String into Integer (TypeError)` which is too technical and vague for end-users. Therefore, surface a more comprehensive message with additional context.

## Context

Fixes #9289

## TODO

Perhaps in a future pull request:
- Let users know the error occurred via a Liquid filter or tag.

### CODE REVIEW

File: test/test_filters.rb [hunk 1]
```diff
@@ -958,6 +958,14 @@ def to_liquid
         results = @filter.where(SelectDummy.new, "obj", "1 == 1")
         assert_equal [], results
       end
+
+      should "gracefully handle invalid property type" do
+        hash = {
+          "members" => { "name" => %w(John Jane Jimmy) },
+          "roles"   => %w(Admin Recruiter Manager),
+        }
+        assert_raises(TypeError) { @filter.where(hash, "name", "Jimmy") }
```
Comment (parkr) [inline test/test_filters.rb:967]: Hm, I think we want to add an assertion on the message here; this would pass without your change I think, so there's no way to know if we broke it.

File: lib/jekyll/filters.rb [hunk 2]
```diff
@@ -441,6 +441,14 @@ def read_liquid_attribute(liquid_data, property)
       property.split(".").reduce(liquid_data) do |data, key|
         data.respond_to?(:[]) && data[key]
       end
+    rescue StandardError => e
+      msg = if liquid_data.is_a?(Array)
+              "Error accessing object (#{liquid_data}) with given key. Expected an integer but " \
+                "got #{property.inspect} instead"
+            else
+              "Error accessing object with key #{property}. #{e.message}"
```
Comment (parkr) [inline lib/jekyll/filters.rb:449]: I believe this line is untested?

File: test/test_filters.rb (hunk 1 above)
Comment (ashmaroli) [reply test/test_filters.rb]: Added an assertion.

File: lib/jekyll/filters.rb [hunk 3]
```diff
@@ -441,6 +441,12 @@ def read_liquid_attribute(liquid_data, property)
       property.split(".").reduce(liquid_data) do |data, key|
         data.respond_to?(:[]) && data[key]
       end
+    rescue StandardError => e
```
Comment (parkr) [inline lib/jekyll/filters.rb:444]: Is StandardError too broad? Should we keep it to TypeError or only catch when we see the error message you mention in the PR description?

File: lib/jekyll/filters.rb [hunk 4]
```diff
@@ -441,6 +441,12 @@ def read_liquid_attribute(liquid_data, property)
...
+      msg = if liquid_data.is_a?(Array)
+              "Error accessing object (#{liquid_data}) with given key. Expected an integer but " \
+                "got #{property.inspect} instead"
+            end
+      raise e, msg
```
Comment (parkr) [inline lib/jekyll/filters.rb:449]: What happens if msg is nil?

**Review by parkr — APPROVED** [review]

**Comment by ashmaroli** [comment]
@jekyllbot: merge +fix
