### PR TITLE
Fix #5233: Increase our ability to detect Windows.

### LINKED ISSUE #5233: jekyll serve not working on Windows Subsystem for Linux
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***Windows*** 10+

---

- [x] It was another bug.

## My Reproduction Steps

```
jekyll serve
Configuration file: /path/to/_config.yml
            Source: /path/to
       Destination: /path/to/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.062 seconds.
jekyll 3.1.6 | Error:  Invalid argument - Failed to watch "/path/to/.git/hooks": the given event mask contains no legal events; or fd is not an inotify file descriptor.
```

This is almost certainly due to https://github.com/Microsoft/BashOnWindows/issues/216. I'm not sure if there's any viable workaround at the moment, but figured (1) it was worth bringing this to the jekyll team's attention, and (2) having a public issue for other users who run into this problem.

### PR DESCRIPTION
**Pull request by envygeeks**
This increases our ability to detect Windows, and to detect Windows+Bash.  It also adds a message to Windows for users who try to "--watch", also noting to to them to check out the Windows ticket so eventually somebody pings us if this issue is fixed. /cc @TAGraves

/cc @jekyll/windows @jekyll/core @parkr @benbalter @jekyll/build

### CODE REVIEW

File: lib/jekyll/utils/platforms.rb [hunk 1]
```diff
@@ -13,18 +13,40 @@ module Platforms
...
+      def windows?
+        !!(RbConfig::CONFIG["host_os"] =~ %r!mswin|mingw|cygwin!i || \
+          proc_version =~ %r!microsoft!i)
+      end
+
+      #
+
+      def linux?
+        RbConfig::CONFIG["host_host"] =~ %r!linux! && \
+          !proc_version =~ %r!microsoft!i
```
Comment (parkr) [inline lib/jekyll/utils/platforms.rb]: I might be remembering Lua, but is this `!~`?

Comment (envygeeks) [inline lib/jekyll/utils/platforms.rb]: You're right, I was in a hurry and doing it on my tablet, I'll ship a correction.

**Comment by parkr** [comment]
Love it!!!!!

File: lib/jekyll/utils/platforms.rb (hunk 1 above)
Comment (envygeeks) [inline lib/jekyll/utils/platforms.rb]: Fixed.

File: lib/jekyll/utils/platforms.rb [hunk 2]
```diff
@@ -13,18 +13,44 @@ module Platforms
         end
       end
 
+      #
+
+      def windows?
+        !!(RbConfig::CONFIG["host_os"] =~ %r!mswin|mingw|cygwin!i || \
```
Comment (XhmikosR) [inline lib/jekyll/utils/platforms.rb]: How about `x64_mingw`? Does this work right there?

Comment (spudowiar) [inline lib/jekyll/utils/platforms.rb]: Looks to me like the regex isn't anchored so it'd match `x64_mingw`

File: lib/jekyll/commands/build.rb [hunk 3]
```diff
@@ -71,12 +71,23 @@ def build(site, options)
         #
         # Returns nothing.
         def watch(site, options)
-          External.require_with_graceful_fail "jekyll-watch"
-          watch_method = Jekyll::Watcher.method(:watch)
-          if watch_method.parameters.size == 1
-            watch_method.call(options)
+          if Utils::Platforms.windows?
+            Jekyll.logger.warn "", "--watch unsupported on Windows. "
```
Comment (benbalter) [inline lib/jekyll/commands/build.rb]: Maybe "The --watch flag is unsupported..." for a bit of polish.

Comment (cori) [inline lib/jekyll/commands/build.rb]: Date: Fri, 12 Aug 2016 07:28:39 -0700

File: lib/jekyll/utils/platforms.rb (hunk 2 above)
Comment (envygeeks) [inline lib/jekyll/utils/platforms.rb]: @XhmikosR @spudowiar we don't care if it's x64, as @spudowiar pointed out, that's why it's unanchored, we are only interested if we find a specific keyword.  There could be dozens of builds.

Comment (XhmikosR) [inline lib/jekyll/utils/platforms.rb]: As long as it detects `x64_mingw` as Windows, that's fine.

File: lib/jekyll/commands/build.rb (hunk 3 above)
Comment (envygeeks) [inline lib/jekyll/commands/build.rb]: Done.

**Comment by envygeeks** [comment]
Updated to add `#really_windows?` so that @ashmaroli can skip certain tests if it's actually Windows.

File: lib/jekyll/utils/platforms.rb [hunk 4]
```diff
@@ -13,18 +13,55 @@ module Platforms
...
             RbConfig::CONFIG["host_os"] =~ v
           )
         end
       end
+
+      #
+
+      private
+      def proc_version
+        @cacahed_proc_version ||= begin
```
Comment (ashmaroli) [inline lib/jekyll/utils/platforms.rb]: did you intend it to be @cached_proc_version ?

Comment (envygeeks) [inline lib/jekyll/utils/platforms.rb]: Fixed.

**Comment by parkr** [comment]
LGTM. Any objections from @jekyll/Windows?

**Comment by envygeeks** [comment]
LGTM.

**Comment by envygeeks** [comment]
From our own Windows users this works for them, so it has a LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Comment by ashmaroli** [comment]
@envygeeks, is there a way to detect Windows version or detect if I'm on the default Windows `cmd.exe` instead of bash shell? I miss `autoregeneration` now..
It works properly when using Jekyll 3.2.1 in `cmd.exe` on Windows 7.

**Comment by envygeeks** [comment]
@ashmaroli we do detect tell the difference between BashOnWindows and Windows itself in cmd.exe/PowerShell, the problem is probably in my detector which is a bit extreme in it's handling, it excludes the entirety of Windows even if there is the win32 extension that works with our watchers.

Later today after I get done with some stuff I'll ship a pull that adds `bash_on_windows?` and adjusts https://github.com/jekyll/jekyll/pull/5235/files#diff-47014fa0275ac66de0d2217d362529ffR74 to use that method so that watchers still work on normal Windows in cmd/PowerShell.

**Comment by ashmaroli** [comment]
Awesome!! Thanks :smiley:

**Comment by parkr** [comment]
@envygeeks Planning to release 3.3 tomorrow so if you want that change in 3.3, we'll need the pull today. If not, then we can release later.

**Comment by envygeeks** [comment]
I'll push it sometime this evening after I get done working.
