### PR TITLE
Excerpt handling of custom and intermediate tags

### LINKED ISSUE #7380: Excerpt handling in 3.8.5 generates Liquid errors despite valid Liquid syntax
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu 18.04.1 LTS |
| `jekyll`         | 3.8.5     |
| `github-pages`   | no     |

---

## Expected Behaviour

Valid Liquid syntax should not throw errors when excerpted; excerpts should gracefully handle Liquid syntax that is correct in the full page (or at least explain what the issue is). This seems related to the [changes in excerpt handling made in 3.8.5](7250) as I do not get errors using jekyll 3.8.4.

## Current Behavior

In some cases, valid Liquid syntax results in syntax errors related to the excerpt

    Error: A Liquid tag in the excerpt of _test/test.xml couldn't be parsed.
    Error: could not read file /tmp/test/_test/test.xml: undefined method `ancestors' for nil:NilClass

Calling `jekyll _3.8.4_ build` generates no errors. Putting `excerpt: none` in the front matter also eliminates the error.

## Code Sample

This isn't my use case (my use case is generating an RSS file), but here's a minimal working example:

Directory tree:

```
.
├── _config.yml
└── _test
    └── test.xml
```

_config.yml:

```
collections:
    test:
        output:     true
```

_test/test.xml:

```
---
---

{% if true %}
xyzzy
{% else %}
plugh
{% endif %}
```

Output:

```
$ jekyll build
Configuration file: /tmp/test/_config.yml
            Source: /tmp/test
       Destination: /tmp/test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: A Liquid tag in the excerpt of _test/test.xml couldn't be parsed.
             Error: could not read file /tmp/test/_test/test.xml: undefined method `ancestors' for nil:NilClass
                    done in 0.012 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

### PR DESCRIPTION
**Pull request by kylebarbour**
This is a 🐛 bug fix.

## Summary

Resolves #7380. This updates `lib/jekyll/excerpts.rb` to improve handling of Liquid blocks which are not properly closed in the excerpt. User-defined custom blocks can now be auto-closed and intermediate logic in blocks (e.g. `else`, `elsif`, `break`, and `continue`) no longer generate issues.

### CODE REVIEW

File: test/source/_plugins/custom_block.rb [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+module Jekyll
+  class DoNothingBlock < Liquid::Block
+  end
+
+  class DoNothingOther < Liquid::Tag
+  end
+end
+
+Liquid::Template.register_tag("do_nothing", DoNothingBlock)
+Liquid::Template.register_tag("do_nothing_other", DoNothingOther)
```
Comment (ashmaroli) [inline test/source/_plugins/custom_block.rb]: These should be under the `Jekyll` namespace..
```ruby
Liquid::Template.register_tag("do_nothing", Jekyll::DoNothingBlock)
Liquid::Template.register_tag("do_nothing_other", Jekyll::DoNothingOther)
```

File: test/test_excerpt.rb [hunk 2]
```diff
@@ -274,4 +274,29 @@ def do_render(document)
...
+  context "An excerpt with Liquid tags" do
+    setup do
+      clear_dest
+      @site = fixture_site
+      @post = setup_post("2018-11-15-excerpt-liquid-block.md")
+      @excerpt = @post.data["excerpt"]
+
+      assert_includes @post.content.split("\n\n")[0].strip, "{% continue %}"
+      assert_equal true, DoNothingBlock.ancestors.include?(Liquid::Block)
+      assert_equal false, DoNothingOther.ancestors.include?(Liquid::Block)
```
Comment (ashmaroli) [inline test/test_excerpt.rb]: Here as well..
```ruby
      assert_equal true, Jekyll::DoNothingBlock.ancestors.include?(Liquid::Block)
      assert_equal false, Jekyll::DoNothingOther.ancestors.include?(Liquid::Block)
```

File: test/source/_plugins/custom_block.rb (hunk 1 above)
Comment (kylebarbour) [reply test/source/_plugins/custom_block.rb]: Doesn't putting them in `module Jekyll` automatically do that? When I tested it looked like they were.

File: test/test_excerpt.rb (hunk 2 above)
Comment (kylebarbour) [reply test/test_excerpt.rb]: I'll update and add that :)

File: test/source/_plugins/custom_block.rb (hunk 1 above)
Comment (kylebarbour) [reply test/source/_plugins/custom_block.rb]: I've added the test below which seems to confirm that they're in the `Jekyll` namespace.

Comment (ashmaroli) [reply test/source/_plugins/custom_block.rb]: Only if `Liquid` is registering the tag within the `Jekyll` module:
```ruby
module Jekyll
  class DoNothingBlock < Liquid::Block
    # [...]
  end

  Liquid::Template.register_tag("do_nothing", DoNothingBlock)
end

Comment (kylebarbour) [reply test/source/_plugins/custom_block.rb]: I'm so sorry to be dumb, but isn't that what's written above?

Comment (ashmaroli) [reply test/source/_plugins/custom_block.rb]: Do not be sorry. What I see in your plugin is:
```ruby
module Jekyll
  class DoNothingBlock < Liquid::Block
    # [...]
  end
end

Liquid::Template.register_tag("do_nothing", DoNothingBlock)
```

Comment (kylebarbour) [reply test/source/_plugins/custom_block.rb]: Can `assert_match "Jekyll::DoNothingBlock"` pass if it's not in the Jekyll namespace though?

Comment (ashmaroli) [reply test/source/_plugins/custom_block.rb]: It should raise an `uninitialized constant` exception, ideally. But honestly, I do not know why the tests are passing.

I extracted your "plugin" into a freshly generated Jekyll Project and it failed as expected..
:man_shrugging:

Comment (kylebarbour) [reply test/source/_plugins/custom_block.rb]: OK! I'll just set it to be as you suggest :)

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Comment by ashmaroli** [comment]
@DirtyF This needs to be back-ported to `3.8-stable` too.. (Just a reminder)
