### PR TITLE
Windows CI on GitHub Actions

### LINKED ISSUE #9636: [Bug]: CI Appveyor 2.7 builds fail
### Operating System

Windows

### Ruby Version

Environment: RUBY_FOLDER_VER=27, TZINFO_VERSION=~> 1.2, TEST_SUITE=test

### Jekyll Version

jekyll 4.3.3

### GitHub Pages Version

Latest

### Expected Behavior

I expected a green build, perhaps only using non-EOL'd Ruby versions.

### Current Behavior

https://ci.appveyor.com/project/jekyll/jekyll/builds/50207910 uses a too-new Bundler (2.5.13) for it work.

### Relevant log output

```shell
bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS%
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: already initialized constant Bundler::CompactIndexClient::SUPPORTED_DIGESTS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: previous definition of SUPPORTED_DIGESTS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: already initialized constant Bundler::CompactIndexClient::DEBUG_MUTEX
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: previous definition of DEBUG_MUTEX was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: already initialized constant Bundler::CompactIndexClient::INFO_NAME
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: previous definition of INFO_NAME was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: already initialized constant Bundler::CompactIndexClient::INFO_VERSION
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: previous definition of INFO_VERSION was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: already initialized constant Bundler::CompactIndexClient::INFO_PLATFORM
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: previous definition of INFO_PLATFORM was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: already initialized constant Bundler::CompactIndexClient::INFO_DEPS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: previous definition of INFO_DEPS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: already initialized constant Bundler::CompactIndexClient::INFO_REQS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: previous definition of INFO_REQS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: already initialized constant Bundler::CompactIndexClient::SUPPORTED_DIGESTS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: previous definition of SUPPORTED_DIGESTS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: already initialized constant Bundler::CompactIndexClient::DEBUG_MUTEX
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: previous definition of DEBUG_MUTEX was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: already initialized constant Bundler::CompactIndexClient::INFO_NAME
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: previous definition of INFO_NAME was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: already initialized constant Bundler::CompactIndexClient::INFO_VERSION
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: previous definition of INFO_VERSION was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: already initialized constant Bundler::CompactIndexClient::INFO_PLATFORM
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: previous definition of INFO_PLATFORM was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: already initialized constant Bundler::CompactIndexClient::INFO_DEPS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: previous definition of INFO_DEPS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: already initialized constant Bundler::CompactIndexClient::INFO_REQS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: previous definition of INFO_REQS was here
--- ERROR REPORT TEMPLATE -------------------------------------------------------

SyntaxError: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client/cache.rb:46: syntax error, unexpected '=', expecting ';' or '\n'
      def names_path = directory.join("names")
                     ^
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client/cache.rb:47: syntax error, unexpected '=', expecting ';' or '\n'
```

### Code Sample

See https://ci.appveyor.com/project/jekyll/jekyll/builds/50207910

### PR DESCRIPTION
**Pull request by ashmaroli**
## Summary

Migrating Windows CI from AppVeyor to GitHub Actions

## Context

Closes #9636
Closes #9657

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hello @parkr, may I request you to uninstall or disable the **AppVeyor** GitHub App from this repository?

**Comment by parkr** [comment]
Thanks so much, @ashmaroli! Based on the settings, if you remove the `appveyor.yaml` file, it should stop building.

File: test/helper.rb [hunk 1]
```diff
@@ -93,6 +93,22 @@ def temp_dir(*subdirs)
   end
 end
 
+module Jekyll
+  class ModifiedReader < Reader
+    def read_directories(dir = "")
+      if dir.start_with?("/symlink") && Utils::Platforms.really_windows?
```
Comment (parkr) [inline test/helper.rb:99]: Is this a bug in Jekyll that's never worked properly on Windows? Or, since symlinks aren't a thing, we don't need to be worried about it? Do you happen to know how Git on Windows handles cloning a repository with symlinks?

Comment (ashmaroli) [reply test/helper.rb:99]: Its **not a bug in Jekyll**, but some discrepancy elsewhere in Windows.
My local Windows 11 system doesn't honor the symlinks in the `test/source` directory. But now that you mentioned it, I'm not sure if it's a cloning issue or system issue because the **`windows-latest`** image on GitHub Actions do acknowledge those symlinks just like the Ubuntu image.

Comment (parkr) [reply test/helper.rb:99]: Ok! Thanks for checking and adding the necessary code.

**Comment by ashmaroli** [comment]
@parkr The reason I had to monkey-patch a Jekyll core class in `test/helper.rb` was because unlike AppVeyor and my local windows machine,  GitHub Actions on Windows follows the symlink to `/etc/password` (just like on Linux) but fails because the path `/etc/password` doesn't exist on a Windows system (which causes `File.realpath(...)` to fail).

If you get the time to push a new symlink-outside-source test file that points to some file which exists on all platforms (e.g. `jekyll.gemspec`), I could remove that monkey-patch from this branch after adjusting all test-failures as a side-effect of symlink-change.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev
