### PR TITLE
filters: raise error if no input given to date filters

### LINKED ISSUE #5107: Filters#time should NOT exit; it should raise an error
If you have the Liquid `{{ "" | date_to_xml_string }}`, it will explode with the error:

```text
 Invalid Date: '' is not a valid datetime.
  Liquid Exception: exit in sitemap.xml
```

We should not use `exit(1)` or `abort` in any of our liquid processing code. This should be replaced with a custom error.

@ayastreb, @pathawks, either one of you want to fix this? 😄  Should be fairly straight-forward.

### PR DESCRIPTION
**Pull request by ayastreb**
Fixes #5107

### CODE REVIEW

File: lib/jekyll/filters.rb [hunk 1]
```diff
@@ -373,8 +373,8 @@ def time(input)
       when Numeric
         Time.at(input)
       else
-        Jekyll.logger.error "Invalid Date:", "'#{input}' is not a valid datetime."
-        exit(1)
+        raise Errors::InvalidDateError,
+          "Invalid Date: '#{input}' is not a valid datetime."
```
Comment (ayastreb) [inline lib/jekyll/filters.rb]: I'm not sure about error message here.
Theoretically it should only get here if input is not given, so maybe it should be something like:
`No input given to filter #{filter_name} in #{document_path}` ?
Can we determine somehow the path of the document where the error is?

Comment (parkr) [inline lib/jekyll/filters.rb]: @ayastreb When an error is raised in Liquid, the renderer catches that and prints the document for which the error occurred so that's all take care of. What's important is to ensure the input is displayed properly. How about `"Invalid Date: \"#{input.inspect}\" is not a valid time."` ?

Comment (parkr) [inline lib/jekyll/filters.rb]: Adding the `.inspect` call means instead of `Invalid Date: "" is not a valid datetime.`, you'd see `Invalid Date: "nil" is not a valid datetime.`

**Comment by parkr** [comment]
LGTM!

**Comment by ayastreb** [comment]
@parkr, yes that sounds good! I've chnaged the error message to include `.inspect`.

**Comment by parkr** [comment]
LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge +bug
