### PR TITLE
Assert raising Psych::SyntaxError when `"strict_front_matter"=>true`

### LINKED ISSUE #6515: JRuby build is failing
All PRs are currently failing CI because the JRuby build is failing 😭😭😭

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #6515 (as well..)

### CODE REVIEW

File: lib/jekyll/document.rb [hunk 1]
```diff
@@ -266,7 +266,7 @@ def read(opts = {})
           merge_defaults
           read_content(opts)
           read_post_data
-        rescue StandardError => e
+        rescue SyntaxError, StandardError, Errors::FatalException => e
```
Comment (pathawks) [inline lib/jekyll/document.rb]: Can you explain what's going on here? Why are we rescuing `FatalException`?

Comment (ashmaroli) [reply lib/jekyll/document.rb]: Because `:handle_read_error` is:
```ruby
    private
    def handle_read_error(error)
      if error.is_a? SyntaxError
        Jekyll.logger.error "Error:", "YAML Exception reading #{path}: #{error.message}"
      else
        Jekyll.logger.error "Error:", "could not read file #{path}: #{error.message}"
      end

      if site.config["strict_front_matter"] || error.is_a?(Jekyll::Errors::FatalException)
        raise error
      end
    end
```
My understanding is that unless `Errors::FatalException` is rescued here, the variable `e` is not going be a subclass of our `Errors::FatalException`

What say, @parkr ?

Comment (pathawks) [reply lib/jekyll/document.rb]: That doesn't make any sense. We rescue `FatalException` only so that we can rethrow it?

Comment (pathawks) [reply lib/jekyll/document.rb]: Oh, because we need to print the error message about not reading the file. Gotcha 👌

Comment (ashmaroli) [reply lib/jekyll/document.rb]: Right.. and `Errors::FatalException` is only a subclass of Ruby's `RuntimeError` (which is the default for a bare `raise`), and not a true `fatal` which is documented as `"impossible to rescue"`

Comment (ashmaroli) [reply lib/jekyll/document.rb]: @pathawks  this change is not actually required for this PR.. do you want me to remove this change so the tests can patched faster?

**Comment by pathawks** [comment]
@jekyllbot: merge +dev

**Comment by parkr** [comment]
This changes “production” code so I’d call it a bug fix if anything. I’m concerned as to why the ::SyntaxError is caught (a syntax error in ruby comes to mind) instead of a ::Psych::SyntaxError but I trust y’all :)

**Comment by ashmaroli** [comment]
> I’m concerned as to why the ::SyntaxError is caught (a syntax error in ruby comes to mind) instead of a ::Psych::SyntaxError

You're rightly concerned. There was [already a PR](https://github.com/jekyll/jekyll/pull/5828) proposing to `rescue` from `::Psych::SyntaxError`. I thought since he brought the matter to light first, he should get a fair chance to contribute.

File: lib/jekyll/document.rb (hunk 1 above)
Comment (jmhooper) [reply lib/jekyll/document.rb]: Since `SyntaxError` and `Jekyll::Errors::FatalException` are subclasses of `StandardError`, rescuing from `StandardError` should collect them as well.

For example, in this code:

```ruby
class ASDFError < StandardError; end

def raise_error
  raise ASDFError
end

begin
  raise_error
rescue StandardError => e
  if e.is_a? ASDFError
    puts 'ASDF Error occured'
  else
    puts "Another error occured"
  end
end
```

...rescuing from `StandardError` still collects the `ASDFError`, and logs that an `ASDFError` occurs.
